apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance1-mongo
  namespace: attendance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance1-mongo
  template:
    metadata:
      labels:
        app: attendance1-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: attendance_db
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


